### ISSUE TITLE
Привет

### ISSUE THREAD

**Issue by Bormental** [bentezhniy/miui-v7-ukrainian#1]
Привет. Рад, что не забрасываешь украинский перевод. Но в репозитории https://github.com/bentezhniy/miui-v7-ukrainian корневой должна быть папка с названием языка (Ukrainian или любое другое слово), а в ней уже device, main, extra.
А то барт каждую из этих папок как отдельный язык понимает.
Например:
[15.09.2015 22:52:55.923] I: Language folders found: 3
[15.09.2015 22:52:55.931] I:     Language 1: device
[15.09.2015 22:52:56.027] I:     Language 2: extras
[15.09.2015 22:52:59.237] I:     Language 3: main

**Comment by BurgerZ** [comment]
Может проще мне в барте проверку сделать - есть папки main/device/extras, то пропускать поиск языков

**Comment by Bormental** [comment]
Оно, конечно, можно, но с языками имхо аккуратней выглядит. Я, например, создал язык International, где все ресы, не привязанные к конкретному языку. Очень удобно.
Спасибо тебе за то, что не бросаешь барта!

**Comment by BurgerZ** [comment]
О, а тут по-русски шпрехаешь)) 
В общем, сделаю проверку, мало ли кто сделает без языка.

**Comment by Bormental** [comment]
Ну тут-то все свои ;)
